### ISSUE TITLE
Make np04_hd apparatus id send to elog

### ISSUE THREAD

**Issue by wesketchum** [alessandrothea/nanorc#150]
Need to make full detector runs integrated into np04 elog. Think we've generally agreed on `np04_hd` as the apparatus id.

This _should_ go to `patch/v3.2.x`.

**Comment by plasorak** [comment]
Which elog should it log to? https://pdsp-elog.cern.ch/elisa/display ?

**Comment by glehmannmiotto** [comment]
yes, it's NP04 so the old SP....

**Comment by plasorak** [comment]
https://github.com/DUNE-DAQ/nanorc/pull/151 Should solve this issue

**Comment by plasorak** [comment]
(tested here: https://pdsp-elog.cern.ch/elisa/display/19047)

**Comment by plasorak** [comment]
Done
