### ISSUE TITLE
NanoRC doesn't like caps in paths

### ISSUE THREAD

**Issue by ArturSztuc** [alessandrothea/nanorc#211]
The recent changes to nanorc made it complain when the config paths/filenames have caps in them.
I think it's [THESE](https://github.com/DUNE-DAQ/nanorc/commit/9ef92b5f040c4f9b907fddb506512141362de738#diff-4bf92100a3983c7410fd0a4332d656f02c4cb6eb86f76d26d64518f3350301d2L67-L69) lines, but I'm not 100% sure.

I'm attaching a file with the error messages.
[errorlog.txt](https://github.com/DUNE-DAQ/nanorc/files/12096305/errorlog.txt)

**Comment by plasorak** [comment]
This has been fixed
