### ISSUE TITLE
Path checking problems for expert command, import and export in integration test

### ISSUE THREAD

**Issue by LJoyL** [alessandrothea/nanorc#218]
Can't implement expert_command with path to module name with error "Couldn't find {prompted_path} in the tree" because the tree has not yet been populate by the others commands.

Looks like the path is being checked before the execution time of the command here : ["@accept_path(argument=True)"](https://github.com/DUNE-DAQ/nanorc/blob/develop/src/nanorc/common_commands.py#L257).

hot fix on my local nanorc :
replace @accept_path(argument=True) by @click.argument('node-path', type=str)

[Move the node check and retrive it when sending the command](https://github.com/DUNE-DAQ/nanorc/blob/develop/src/nanorc/core.py#L155).
```
# Check path validity when sending the command and not before for integtest compatibility
topnode = self.topnode
node = None
r = Resolver('name')
try:
    node = r.get(topnode, node_path)
except Exception as ex:
    raise click.BadParameter(f"Couldn't find {node_path} in the tree") from ex
```

**Comment by plasorak** [comment]
Hi Leo, I think this is an acceptable solution, would you be able to create a PR with it? Thanks.

**Comment by plasorak** [comment]
This has been merged and worked right?
