### ISSUE TITLE
nano04rc Skip elisa service account request if connection not defined in .nano04rc

### ISSUE THREAD

**Issue by alessandrothea** [alessandrothea/nanorc#264]
Also, maybe the service account name should be configurable...

**Comment by plasorak** [comment]
We've just tried with @PawelPlesniak, it is configurable, if you modify `~/.nanorc.json`: `"cern"."authentication"."elisa"."user"` to be your user name, it will ask twice for your password, and log in as you for elisa purposes. Pawel also made the modification when ELisA isn't required.

**Comment by alessandrothea** [comment]
Perfect, thanks!
