### ISSUE TITLE
Run Control GUI

### ISSUE THREAD

**Issue by bieryAtFnal** [alessandrothea/nanorc#71]
I'm creating this Issue (with Zbynek's permission) as a placeholder for the work that he is doing on the RC GUI.  The purpose of the placeholder is to allow us to keep track of which release the work is planned for, etc.

**Comment by bieryAtFnal** [comment]
Zbynek has provided instructions: https://github.com/DUNE-DAQ/nanorc/wiki/Testing-Web-GUI

**Comment by bieryAtFnal** [comment]
"pip install -U ." of the plasorak/web_and_rest_nanorc branch of nanorc errors out for me on np04-srv-013 with the following error:
```
ERROR: Command errored out with exit status 1: /nfs/home/biery/dunedaq/19AprDevTest/dbt-pyvenv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/nfs/home/biery/dunedaq/19AprDevTest/nanorc/setup.py'"'"'; __file__='"'"'/nfs/home/biery/dunedaq/19AprDevTest/nanorc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/biery/pip-record-aidrmno7/install-record.txt --single-version-externally-managed --compile --install-headers /nfs/home/biery/dunedaq/19AprDevTest/dbt-pyvenv/include/site/python3.8/nanorc Check the logs for full command output.
```

**Comment by plasorak** [comment]
I just realised there is no PR for this. I'm going to create it.

**Comment by plasorak** [comment]
I'm going to have a look at the error Kurt, thanks for trying.

**Comment by plasorak** [comment]
I've fixed the issue in the PR @bieryAtFnal
