### ISSUE TITLE
Better GUI for Nanorc

### ISSUE THREAD

**Issue by plasorak** [alessandrothea/nanorc#82]
We need a better GUI for the next iterations:
 - The REST should expose all the available commands on a given state and their arguments.
 - Above will allow the inclusion of custom commands for free.
 - Will also get the np04 prod environment GUI for free.
 - Access the logs directly from the GUI, through an endpoint.

**Comment by cvzbynek** [comment]
Popup window
Datatypes
Required or not
Basic validation

**Comment by plasorak** [comment]
After further testing, the GUI should also be able to understand another parameter type:
```
    {
      "run_type": {
        "default": null, 
        "required": true, 
        "type": "Choice(['TEST', 'PROD'])"
      }
    }, 
```
And give a dropdown menu to the user where he/she can choose.

**Comment by plasorak** [comment]
(that can be change of course to something a bit more simple)

**Comment by plasorak** [comment]
To test it:
 - checkout nanorc and cd into it
 - `git checkout feature/better-gui`
 - `pip install -e .`
 - `nanorc --web the_conf` or `nano04rc --web the_conf` or `nanotimingrc --web the_conf`

**Comment by plasorak** [comment]
This has been merged a while ago too
