### ISSUE TITLE
env vars not passed to daq applications in the current --k8s development environment

### ISSUE THREAD

**Issue by ron003** [alessandrothea/nanorc#86]
Pierre has confirmed on the daq-ccm channel that the env.vars. are currently not being passed correctly

**Comment by tapperad** [comment]
This is linked to the issue on changes to boot.json for k8s -- trivial when that's completed.

**Comment by tapperad** [comment]
@ron003 Will this solve this second of your pocket issues in the Triage category?

https://github.com/DUNE-DAQ/pocket/issues/18

**Comment by ron003** [comment]
I don't think it will solve the issue, but there will be a workaround as long as the TRACE_FILE env can be set.
In order to solve it, there should be an attempt to strip the host prefix to the shared area from the TRACE_FILE path before passing it to the container environment.

**Comment by plasorak** [comment]
I think this is done too, I'll let Ron reopen the issue if something still needs to be fixed.

**Comment by plasorak** [comment]
Hi @ron003 going back to this, is it not possible for a developper who wants to do TRACE debugging to get on the pod?
The following will get your a bash shell in the pod:
```
kubectl exec --stdin --tty the_pod_name -- /bin/bash
```
And then setup `dunedaq` from there and do traces?

**Comment by ron003** [comment]
This issue is about the environment variables...
In order for the application to do TRACEing, at least one of the "TRACE activating" environment variables must be set in it's environment (i.e before the application executes the TLOG debug statements)
So, logging into the pod after the application has started (if that is what you're talking about) would be too late.
