### ISSUE TITLE
Integration tests for nanorc

### ISSUE THREAD

**Issue by plasorak** [alessandrothea/nanorc#90]
Probably good to, at some point, have the following tests:
 - everything works with 2 configurations
 - everything works with partiton-number from 0 to 9
 - logs get saved at the correct place
 - … and all of this for `nanorc`, `nanotimingrc`, `nano04rc`
 - and eventually with `k8s`, `kind` and `ssh`

**Comment by plasorak** [comment]
This has been done by @JonathanHancock0

**Comment by bieryAtFnal** [comment]
see [the relevant README file](https://github.com/DUNE-DAQ/nanorc/blob/develop/integtests/README.md) for details...
